echo ---------------ROS ENVIRONMENT------------------------
set | grep ROS
echo ---------------GAZEBO ENVIRONMENT---------------------
echo GAZEBO_MODEL_PATH: $GAZEBO_MODEL_PATH
echo GAZEBO_RESOURCE_PATH: $GAZEBO_RESOURCE_PATH
echo GAZEBO_MEDIA_PATH: $GAZEBO_MEDIA_PATH
echo GAZEBO_MASTER_URI: $GAZEBO_MASTER_URI
echo GAZEBO_IP: $GAZEBO_IP
echo GAZEBO_PORT: $GAZEBO_PORT
echo GAZEBO_MODEL_DATABASE_URI: $GAZEBO_MODEL_DATABASE_URI
echo GAZEBO_PLUGIN_PATH: $GAZEBO_PLUGIN_PATH
echo GAZEBO_MODEL_DATABASE_URI: $GAZEBO_MODEL_DATABASE_URI
echo GAZEBO_MODEL_DATABASE_SCRIPT: $GAZEBO_MODEL_DATABASE_SCRIPT
echo GAZEBO_MODEL_DATABASE_PLUGIN_PATH: $GAZEBO_MODEL_DATABASE_PLUGIN_PATH
echo GAZEBO_MODEL_DATABASE_RESOURCE_PATH: $GAZEBO_MODEL_DATABASE_RESOURCE_PATH
echo GAZEBO_MODEL_DATABASE_MODEL_PATH: $GAZEBO_MODEL_DATABASE_MODEL_PATH
echo GAZEBO_MODEL_DATABASE_URI: $GAZEBO_MODEL_DATABASE_URI